### ISSUE TITLE
[react-docs] Update Model Retrieval Logic and State Management for https://text.pollinations.ai/models

### ISSUE THREAD

**Issue by diogo-karma** [pollinations/pollinations#724]
The current implementation of real-time model retrieval uses a `GET` request that returns an array in the following format:
```json
['openai', 'mistral', 'llama']
```
However, the new API response format has changed to a more complex structure:
```json
[
  {
    "name": "openai",
    "type": "chat",
    "censored": true
  },
  {
    "name": "mistral",
    "type": "completion",
    "censored": false
  },
  {
    "name": "llama",
    "type": "completion",
    "censored": true
  }
]
```
To accommodate this new structure, we need to:
1. Parse the new response format to extract relevant data (i.e., `name`, `type`, and `censored` status).
2. Update the `useState` hook to handle this new structure.
3. Modify the default variables and any components dependent on this state to ensure they correctly interpret the `type` and `censored` fields.
4. Ensure backward compatibility, or update any part of the application that assumes the old format.

#### Tasks:
- [ ] Update the model-fetching logic to handle the new structure.
- [ ] Refactor the `useState` hook to store the additional properties (`type`, `censored`).
- [ ] Adjust the UI or backend logic to properly use the `type` and `censored` fields when rendering or processing models.
- [ ] Test the implementation to ensure smooth real-time updates with the new data structure.
