### ISSUE TITLE
 [React-Hooks/Hooks] Optimize Text Generation using Screen Size, User Agent, and Language

### ISSUE THREAD

**Issue by diogo-karma** [pollinations/pollinations#768]
# Implement a feature to enhance Pollinations' text generation by considering the user's device characteristics and language preferences.

### Feature Overview

1. Detect screen size, user agent, and preferred language(s)
2. Pass this information to the text generation module
3. Adjust generated text based on detected parameters

### Implementation

1. Use existing React hooks to get device info:
   ```javascript
   const { screenSize, userAgent, languages } = useDeviceInfo();
   ```

2. Modify text generation function to accept these parameters:
   ```javascript
   const optimizedText = generateText(prompt, { screenSize, userAgent, languages });
   ```

3. Implement simple optimizations in text generation:
   - Adjust paragraph length for different screen sizes
   - Tailor content for mobile/desktop based on user agent
   - Prioritize detected languages for multilingual content

### Tasks

- [ ] Review and update existing device detection hooks if needed
- [ ] Modify text generation function to accept new parameters
- [ ] Implement basic optimization logic in text generation
- [ ] Add unit tests for new functionality
- [ ] Update documentation with usage examples

### Benefits

- Improved readability across devices
- Better user experience with language-aware content
- Groundwork for future, more advanced optimizations

This small feature will provide a foundation for more context-aware text generation in Pollinations, enhancing the user experience across different devices and languages.
